##############################################################################
# DO NOT EDIT THIS FILE
# The system-dependent settings are in Makefile.in
##############################################################################

GRAPHAM_ROOT=$(shell pwd)
include Makefile.in

ifeq ($(ENVIRONMENT), mingw)
       EXECNAME=grapham.exe
       LN_CMD=cp
else
       EXECNAME=grapham
       LN_CMD=ln -f
endif

.PHONY: clean clib all netlib numlua main

DEFAULT: main
all: netlib numlua clib main

main: netlib numlua
	cd src; make
	$(LN_CMD) src/$(EXECNAME) $(EXECNAME)

numlua:
ifneq ($(NUMLUA_PATH),)
	cd $(NUMLUA_PATH)/src; make
endif

netlib:
	cd netlib; make

clib: main
	cd clib; make

clean:
	rm -f $(EXECNAME)
	cd src; make clean
	cd clib; make clean
	cd netlib; make clean
